import type { LoveReason } from '../types';

export const reasonsData: LoveReason[] = [
  { id: 1, text: 'The way you laugh at my terrible jokes' },
  { id: 2, text: 'Your kindness to strangers' },
  { id: 3, text: 'How you make every place feel like home' },
  { id: 4, text: 'Your beautiful eyes that see the best in me' },
  { id: 5, text: 'The way you hold my hand when I\'m nervous' },
  { id: 6, text: 'Your passion for the things you love' },
  { id: 7, text: 'How you always know what I need' },
  { id: 8, text: 'Your incredible cooking (and burnt toast attempts)' },
  { id: 9, text: 'The way you dance when no one is watching' },
  { id: 10, text: 'Your patience with my quirks' },
  { id: 11, text: 'How you make ordinary days extraordinary' },
  { id: 12, text: 'Your strength during hard times' },
  { id: 13, text: 'The sound of your voice saying my name' },
  { id: 14, text: 'Your adventurous spirit' },
  { id: 15, text: 'How you remember the little things' },
  { id: 16, text: 'Your warm hugs that fix everything' },
  { id: 17, text: 'The way you support my dreams' },
  { id: 18, text: 'Your silly faces that make me smile' },
  { id: 19, text: 'How you light up every room you enter' },
  { id: 20, text: 'Your honesty, even when it\'s hard' },
  { id: 21, text: 'The way you sing in the shower' },
  { id: 22, text: 'Your generosity of spirit' },
  { id: 23, text: 'How you make me want to be better' },
  { id: 24, text: 'Your beautiful soul' },
  { id: 25, text: 'The way you look at me' },
  { id: 26, text: 'Your courage to be vulnerable' },
  { id: 27, text: 'How you fight for what matters' },
  { id: 28, text: 'Your creativity and imagination' },
  { id: 29, text: 'The way you care for our loved ones' },
  { id: 30, text: 'Your morning smile, even before coffee' },
  { id: 31, text: 'How you make me feel safe' },
  { id: 32, text: 'Your wisdom beyond your years' },
  { id: 33, text: 'The way you celebrate my victories' },
  { id: 34, text: 'Your gentle touch' },
  { id: 35, text: 'How you never give up on us' },
  { id: 36, text: 'Your sense of humor' },
  { id: 37, text: 'The way you plan surprise adventures' },
  { id: 38, text: 'Your loyalty and devotion' },
  { id: 39, text: 'How you make silence comfortable' },
  { id: 40, text: 'Your beautiful heart' },
  { id: 41, text: 'The way you say goodnight' },
  { id: 42, text: 'Your resilience through challenges' },
  { id: 43, text: 'How you inspire me daily' },
  { id: 44, text: 'Your playful side' },
  { id: 45, text: 'The way you listen without judgment' },
  { id: 46, text: 'Your dreams for our future' },
  { id: 47, text: 'How you make love feel effortless' },
  { id: 48, text: 'Your grace under pressure' },
  { id: 49, text: 'The way you choose me every day' },
  { id: 50, text: 'Simply because you are you' },
];
