import type { LoveReason } from '../types';

export const reasonsData: LoveReason[] = [
  { id: 1, text: 'you believe in me when I doubt myself' },
  { id: 2, text: 'you are beautiful inside and out' },
  { id: 3, text: 'you are my best friend' },
  { id: 4, text: 'your smile whichcan brighten even my worst day' },
  { id: 5, text: 'you are my favorite person to hang out with' },
  { id: 6, text: 'the way you value my opinions' },
  { id: 7, text: 'you understand me well even when iam wrong you are calm' },
  { id: 8, text: 'you give me btter life advices' },
  { id: 9, text: 'the way you are ambitious toward your career' },
  { id: 10, text: 'you dont lie to me ' },
  { id: 11, text: 'you make me feel valued' },
  { id: 12, text: 'the way you support my dreams' },
  { id: 13, text: 'that day when i cried you consoled me right , i was so grateful' },
  { id: 14, text: 'even when i think low you motivate to set high standards' },
  { id: 15, text: 'i like the way you are so affectionate towards your parents' },
  { id: 16, text: 'your baby voice with which you speak to your mom (iwant you to speak the same with me)' },
  { id: 17, text: 'you have a great sense of humor but less than me hahaha' },
  { id: 18, text: 'you dont break promises and value it' },
  { id: 19, text: 'by the way you behave i have immense trust on you' },
  { id: 20, text: 'you are the first person / thought that comes to my mind every morning and night' },
  { id: 21, text: 'your daily one time pic ( i love it)' },
  { id: 22, text: 'your hug which makes me feel everything okay' },
  { id: 23, text: 'your determination towards studies' },
  { id: 24, text: '' },
  { id: 25, text: '' },
  { id: 26, text: '' },
  { id: 27, text: '' },
  { id: 28, text: '' },
  { id: 29, text: '' },
  { id: 30, text: '' },
  { id: 31, text: '' },
  { id: 32, text: '' },
  { id: 33, text: '' },
  { id: 34, text: '' },
  { id: 35, text: '' },
  { id: 36, text: '' },
  { id: 37, text: '' },
  { id: 38, text: '' },
  { id: 39, text: '' },
  { id: 40, text: '' },
  { id: 41, text: '' },
  { id: 42, text: '' },
  { id: 43, text: '' },
  { id: 44, text: '' },
  { id: 45, text: '' },
  { id: 46, text: '' },
  { id: 47, text: '' },
  { id: 48, text: '' },
  { id: 49, text: '' },
  { id: 50, text: '' },
];
